
$scriptFolder = Split-Path -Parent $MyInvocation.MyCommand.Definition
$projRoot = Split-Path -Parent $scriptFolder 

Push-Location $projRoot

$proxyExe = Join-Path $projRoot "proxy.exe"
$logDir = Join-Path $projRoot "logs"
$sampleLog = Join-Path $logDir "sample_run.log"
$proxyLogFile = Join-Path $logDir "proxy.log"


if (!(Test-Path $logDir)) { 
    New-Item -ItemType Directory -Path $logDir | Out-Null 
}


if (!(Test-Path $proxyExe)) {
    Write-Error "ERROR: proxy.exe not found at $proxyExe. Build the project first!"
    Pop-Location
    Exit 1
}


if (Test-Path $sampleLog) { Remove-Item $sampleLog }


function Stop-Proxy($p) {
    if ($p -and !$p.HasExited) {
        Write-Host "Stopping proxy..."
        $p.Kill()
        $p.WaitForExit()
    }
}

try {
  
    Write-Host "Starting proxy to generate activity..."
    $proc = Start-Process -FilePath $proxyExe -NoNewWindow -PassThru
    Start-Sleep -Seconds 2

    
    Write-Host "Running sample requests..."
    cmd /c "curl.exe -x localhost:8888 -sS http://httpbin.org/get" > "$logDir\sample1.txt" 2>&1
    cmd /c "curl.exe -x localhost:8888 -sS http://example.com" > "$logDir\sample2.txt" 2>&1
    cmd /c "curl.exe -x localhost:8888 -sS -I http://httpbin.org/get" > "$logDir\sample3.txt" 2>&1
    
    Start-Sleep -Seconds 1

    
    Write-Host "Combining logs into $sampleLog..."
    
    "===== SAMPLE RUN LOG GENERATED BY TEST SCRIPT =====" | Out-File -FilePath $sampleLog -Encoding utf8
    "Generated on: $(Get-Date)" | Out-File -FilePath $sampleLog -Append -Encoding utf8
    
    
    foreach ($file in @("sample1.txt", "sample2.txt", "sample3.txt")) {
        $path = Join-Path $logDir $file
        if (Test-Path $path) {
            "`n--- Content of $file ---" | Out-File -FilePath $sampleLog -Append -Encoding utf8
            Get-Content $path | Out-File -FilePath $sampleLog -Append -Encoding utf8
        }
    }

   
    if (Test-Path $proxyLogFile) {
        "`n===== INTERNAL PROXY.LOG CONTENT =====" | Out-File -FilePath $sampleLog -Append -Encoding utf8
        Get-Content $proxyLogFile | Out-File -FilePath $sampleLog -Append -Encoding utf8
    } else {
        Write-Warning "Warning: Internal proxy.log not found. Ensure your C++ code writes to logs/proxy.log."
    }

    Write-Host "Success! Final artifact created at $sampleLog"

} catch {
    Write-Error "An unexpected error occurred during collection: $_"
} finally {

    Stop-Proxy $proc
    Pop-Location
}